# 设置EEPROM磨损均衡
EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor

WPM_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick

SRC += analog.c
