VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
ENCODER_MAP_ENABLE = yes

QMK_SETTINGS = yes
KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
MAGIC_ENABLE = yes
SPACE_CADET_ENABLE = yes
WPM_ENABLE = yes
GRAVE_ESC_ENABLE = yes
POINTING_DEVICE_ENABLE = no
JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = analog
