VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
LTO_ENABLE = yes
VIALRGB_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no
# WPM_ENABLE = no
GRAVE_ESC_ENABLE = no
TAP_DANCE_ENABLE = no
