#ifdef RGB_MATRIX_ENABLE
    #define DRIVER_LED_TOTAL 15
    #define RGB_DI_PIN D3
    #define RGB_MATRIX_KEYPRESSES
    #define ENABLE_RGB_MATRIX_BREATHING
    #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
    #define ENABLE_RGB_MATRIX_HUE_BREATHING
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
    #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#endif
